version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites:/etc/nginx/sites:ro
    depends_on:
      - recipe-app

  recipe-app:
    image: ghcr.io/dezodemius/recipeapp:latest
    ports:
      - "5128:5128"
    restart: unless-stopped
    environment:
      - ASPNETCORE_URLS=http://+:5128
    secrets:
    - ghcr_creds

secrets:
  ghcr_creds:
    file: ./.secrets/ghcr_token

volumes:
  nginx_conf:
  nginx_sites:
