version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-simple
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
